# Generated by Django 5.2.3 on 2025-06-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="bathroom",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="bedroom",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
