# Generated by Django 5.2.3 on 2025-07-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_rent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "category",
                    models.CharField(
                        choices=[("Available", "Available"), ("For Sale", "For Sale")],
                        max_length=20,
                    ),
                ),
                (
                    "category_type",
                    models.CharField(
                        choices=[("Apartment", "Apartment"), ("Property", "Property")],
                        max_length=20,
                    ),
                ),
                ("images", models.ImageField(upload_to="property_images/")),
                (
                    "bathroom",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "bedroom",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="shortlet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "category",
                    models.CharField(
                        choices=[("Available", "Available"), ("For Sale", "For Sale")],
                        max_length=20,
                    ),
                ),
                (
                    "category_type",
                    models.CharField(
                        choices=[("Apartment", "Apartment"), ("Property", "Property")],
                        max_length=20,
                    ),
                ),
                ("images", models.ImageField(upload_to="property_images/")),
                (
                    "bathroom",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "bedroom",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
