# Generated by Django 5.2.3 on 2025-08-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0004_buy_shortlet"),
    ]

    operations = [
        migrations.CreateModel(
            name="land",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "category",
                    models.CharField(
                        choices=[("Available", "Available"), ("For Sale", "For Sale")],
                        max_length=20,
                    ),
                ),
                (
                    "category_type",
                    models.CharField(
                        choices=[("Apartment", "Apartment"), ("land", "land")],
                        max_length=20,
                    ),
                ),
                ("images", models.ImageField(upload_to="property_images/")),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
